---
default: -p acom -b firefox --headless false

dev: 
  baseUrl: http://localhost:3000

preview: 
  baseUrl: https://${branch}--www--webplatformautomation.hlx.page

live: 
  baseUrl: https://${branch}--www--webplatformautomation.hlx.live

origin: 
  baseUrl: https://www.webplatform4.com

acom:
  baseUrl: https://www.adobe.com              # Base URL of pages to be tested
  testBaseUrl: https://www.webplatform4.com   # Where are tests?

